---
# name of the action 
name: Checks

# execute the actions on push (git push)
on: [push]

# Jobs will be executed
jobs:
  # Id of the job (different name)
  test-lint:
    # Id of the job (different name)
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # login to docker hub
      - name: Login to Docker Hub
        # uses allows you to use premade actions on github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # this is the second step to check that the code is available 
      - name: Checkout
        uses: actions/checkout@v2

      # run python unit tests
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      
      # run flake8
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"